### ISSUE TITLE
Cannot use hyphen `foo-bar` in route path

### ISSUE THREAD

**Issue by strickczq** [jvdwrf/axum-typed-routing#3]
got error `unexpected token`

**Comment by jvdwrf** [comment]
Thanks for opening the issue! I have found the issue, when I get a little bit of time I will look in to it.

**Comment by jvdwrf** [comment]
Closed with 5fa46ac.

**Comment by jvdwrf** [comment]
Released v0.2.1 with support for hyphens in path paramaters
