### ISSUE TITLE
Wildcard matching

### ISSUE THREAD

**Issue by Wicpar** [jvdwrf/axum-typed-routing#4]
axum and aide spec allow for wildcard matching /foo/*path, it ssems this library doesn't support it

**Comment by jvdwrf** [comment]
Yea, didn't think about that before.
When I get a bit of time I will add it :)

**Comment by jvdwrf** [comment]
Released v0.2.1 with wildcard support

**Comment by Wicpar** [comment]
wow so fast, nice !

**Comment by svenstaro** [comment]
It looks like this was created but never documented. I didn't even know this feature existed until I looked into the code. @jvdwrf could you add some docs and perhaps an example?
